version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: autopredator.settings
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
