flyway.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}
flyway.connectRetries=10
flyway.schemas=auth,catalog,pricing,market,crm,ops
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.cleanDisabled=true
