# Generated by Django 5.2.8 on 2025-11-17 15:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/', validators=[core.validators.validate_upload_file]),
        ),
    ]
